services:
  server:
    build: .
    ports: 
      - "3000:3000"
    depends_on:
      - redis
    volumes:
      - .:/app
   
        
  redis:
    image: redis/redis-stack:latest
    tty: true
    ports:
      - "6378:6379"
    volumes:
      - go-mock-api_db:/data      
volumes:
  go-mock-api_db:
