services:
  server:
    build: .
    ports: 
      - "3000:3000"
    depends_on:
      - redis
    volumes:
      - .:/app
   
        
  redis:
    image: redis:alpine
    volumes:
      - db:/data      
volumes:
  db: 
