services:
  server:
    container_name: server
    build: .
    tty: true
    stdin_open: true 
    ports: 
      - "3000:3000"
    depends_on:
      - redis
    volumes:
      - .:/app
   
        
  redis:
    image: redis/redis-stack:latest
    tty: true
    ports:
      - "6378:6379"
    volumes:
      - go-mock-api_db:/data     
    environment:
      REDIS_ARGS: --save 20 1 
volumes:
  go-mock-api_db:
    external: false
