services:
  server:
    build: .
    container_name: go-mock-api
    ports: 
      - "3000:3000"
    depends_on:
      - redis

  redis:
    image: redis:alpine
    volumes:
      - db:/data      
volumes:
  db: 